{% set name = "endstate_correction" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wiederm/endstate_correction/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5d6bbf182cbdb1064ec07c3ddda151d7c7b5c476cd89525d5bafc029d41a6d4c

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - openmm >=8.0
    - openmm-torch
    - openff-toolkit
    - openmmtools
    - tqdm
    - pymbar >=4.0
    - torchani
    - seaborn
    - pytorch
    - mdtraj
    - openmm-ml

test:
  imports:
    - endstate_correction
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/wiederm/endstate_correction
  summary: 'Endstate corrections from MM to QML potential'
  description: |
    Following an arbritary thermodynamic cycle to calculate a free 
    energy for a given molecular system at a certain level of theory, 
    we can perform endstate corrections at the nodes of the thermodynamic 
    cycle to a desired target level of theory. In this work we have 
    performed the endstate corrections using equilibrium free energy 
    calculations, non-equilibrium (NEQ) work protocols and free energy 
    perturbation (FEP).
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://wiederm.github.io/endstate_correction/
  dev_url: https://github.com/wiederm/endstate_correction

extra:
  recipe-maintainers:
    - xiki-tempula
    - wiederm
